// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(MARDBContext))]
    [Migration("20231222172026_update order table 3")]
    partial class updateordertable3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Common.DocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DocuementCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocuemntName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DocumentModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefereneceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DocumentItems");
                });

            modelBuilder.Entity("Entities.Models.Common.LookupData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LookupCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LookupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LookupModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LookupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookupType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LookupValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LookupData");
                });

            modelBuilder.Entity("Entities.Models.Common.UsersComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CommentCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CommentModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CommentReviewStars")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentType")
                        .HasColumnType("int");

                    b.Property<int>("RefranceNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsersComments");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductCategoryNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDescritpion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductDiscountNo")
                        .HasColumnType("int");

                    b.Property<int>("ProductInventoryNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryNo")
                        .HasColumnType("int");

                    b.Property<int>("SubOfSubCategoryNo")
                        .HasColumnType("int");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryNo");

                    b.HasIndex("ProductDiscountNo");

                    b.HasIndex("ProductInventoryNo");

                    b.HasIndex("SubCategoryNo");

                    b.HasIndex("SubOfSubCategoryNo");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CategoryCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryDescritpion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CategoryModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.ProductDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DiscountCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountDescritpion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DiscountEnddDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiscountModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiscountStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductDiscounts");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.ProductInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("InventoryCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InventoryDescritpion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InventoryModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InventoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductInventories");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.ProductSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CategoryCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CategoryModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductNo")
                        .HasColumnType("int");

                    b.Property<string>("SpecificationDescritpion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductSpecifications");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CategoryCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryDescritpion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CategoryModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryNo");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.SubOfSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CategoryCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryDescritpion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CategoryModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryNo");

                    b.ToTable("SubOfSubCategory");
                });

            modelBuilder.Entity("Entities.Models.Shopping_Management.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expiry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExporterNo")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeNo")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserNo");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Models.Shopping_Management.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderItemCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderItemModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<int>("ProductNo")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNo");

                    b.HasIndex("ProductNo");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Entities.Models.Shopping_Management.OrderPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PyamentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("Entities.Models.User_Management.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Entities.Models.User_Management.ExporterInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ExportPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ExporterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FrightPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SocialInsuracePrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserNo");

                    b.ToTable("Exporters");
                });

            modelBuilder.Entity("Entities.Models.User_Management.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserPaymentInformationNo")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Models.User_Management.UserOrderAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserNo");

                    b.ToTable("UserOrderAddresses");
                });

            modelBuilder.Entity("Entities.Models.User_Management.UserPaymentInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expiry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserPaymentInformations");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.Product", b =>
                {
                    b.HasOne("Entities.Models.Product_Management.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product_Management.ProductDiscount", "ProductDiscount")
                        .WithMany()
                        .HasForeignKey("ProductDiscountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product_Management.ProductInventory", "ProductInventory")
                        .WithMany()
                        .HasForeignKey("ProductInventoryNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product_Management.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product_Management.SubOfSubCategory", "SubOfSubCategory")
                        .WithMany()
                        .HasForeignKey("SubOfSubCategoryNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductDiscount");

                    b.Navigation("ProductInventory");

                    b.Navigation("SubCategory");

                    b.Navigation("SubOfSubCategory");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.SubCategory", b =>
                {
                    b.HasOne("Entities.Models.Product_Management.ProductCategory", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("CategoryNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("Entities.Models.Product_Management.SubOfSubCategory", b =>
                {
                    b.HasOne("Entities.Models.Product_Management.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Entities.Models.Shopping_Management.Order", b =>
                {
                    b.HasOne("Entities.Models.User_Management.User", "User")
                        .WithMany()
                        .HasForeignKey("UserNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Shopping_Management.OrderItem", b =>
                {
                    b.HasOne("Entities.Models.Shopping_Management.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Product_Management.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.User_Management.ExporterInformation", b =>
                {
                    b.HasOne("Entities.Models.User_Management.User", "User")
                        .WithMany()
                        .HasForeignKey("UserNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.User_Management.UserOrderAddress", b =>
                {
                    b.HasOne("Entities.Models.User_Management.User", "User")
                        .WithMany()
                        .HasForeignKey("UserNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
